name: "Minikube (Single node Kubernetes) Action"
description: "Sets up Minikube for your Github Actions."
author: "OpsGang"
inputs:
  minikube-version:
    description: "Version of Minikube to use. Default: 1.4.0"
    default: "1.4.0"
  k8s-version:
    description: "Version of Kubernetes to use. Default: 1.15.0"
    default: "1.15.0"
runs:
  using: "node12"
  main: "dist/index.js"
